#!/bin/bash
set -eou pipefail

rm -f build.zip
rm -rf build
mkdir build
cp src/* build
cp LICENSE build
cd build
zip ../build.zip *
cd ..
rm -rf build
echo
unzip -l build.zip
echo
unzip -p build.zip manifest.json
